function A(){function ma(a){let c,g,k,b,f,h,e;c=Math.abs(a);var t=l(2147483648+(a>>>31));g=l(t-1-t%c);t=31;b=l(Math.trunc(2147483648/g));f=l(2147483648-b*g);h=l(Math.trunc(2147483648/c));e=l(2147483648-h*c);do t=l(t+1),b=l(2*b),f=l(2*f),f>=g&&(b=l(b+1),f=l(f-g)),h=l(2*h),e=l(2*e),e>=c&&(h=l(h+1),e=l(e-c)),k=l(c-e);while(b<k||b==k&&0==f);this.M=h+1&4294967295;0>a&&(this.M=-this.M);this.s=t-32}function na(a){let c,g,k,b,f,h,e;c=Math.abs(a);var t=32768+((a&65535)>>>15)&65535;g=t-1-t%c&65535;t=15;b=Math.trunc(32768/
g)&65535;f=32768-b*g&65535;h=Math.trunc(32768/c)&65535;e=32768-h*c&65535;do t=t+1&65535,b=2*b&65535,f=2*f&65535,f>=g&&(b=b+1&65535,f=f-g&65535),h=2*h&65535,e=2*e&65535,e>=c&&(h=h+1&65535,e=e-c&65535),k=c-e&65535;while(b<k||b==k&&0==f);this.M=S(h+1);0>a&&(this.M=-this.M);this.s=t-16}function oa(a){let c,g,k,b,f,h;this.a=0;var e=l(~a+1);c=l(4294967295-l(e%a));e=31;k=l(Math.trunc(2147483648/c));b=l(2147483648-k*c);f=l(Math.trunc(2147483647/a));h=l(2147483647-f*a);do e=l(e+1),b>=l(c-b)?(k=l(2*k+1),b=
l(2*b-c)):(k=l(2*k),b=l(2*b)),l(h+1)>=l(a-h)?(2147483647<=f&&(this.a=1),f=l(2*f+1),h=l(2*h+1-a)):(2147483648<=f&&(this.a=1),f=l(2*f),h=l(2*h+1)),g=l(a-1-h);while(64>e&&(k<g||k==g&&0==b));this.M=l(f+1);this.s=e-32}function pa(a){let c,g,k,b,f,h,e;this.a=0;g=65535-((~a+1&65535)%a&65535)&65535;c=15;b=Math.trunc(32768/g)&65535;f=32768-b*g&65535;h=Math.trunc(32767/a)&65535;e=32767-h*a&65535;do c=c+1&65535,f>=(g-f&65535)?(b=2*b+1&65535,f=2*f-g&65535):(b=2*b&65535,f=2*f&65535),(e+1&65535)>=(a-e&65535)?(32767<=
h&&(this.a=1),h=2*h+1&65535,e=2*e+1-a&65535):(32768<=h&&(this.a=1),h=2*h&65535,e=2*e+1&65535),k=a-1-e&65535;while(32>c&&(b<k||b==k&&0==f));this.M=h+1;this.s=c-16}function qa(a){let c=document.getElementById("msgdiv"),g=document.createElement("p");g.setAttribute("class","red");g.append(a);c.append(g)}function ha(){let a=document.getElementById("resultsdiv"),c=document.createElement("div");c.setAttribute("class","srcprogdiv");let g=document.createElement("pre");g.append(Y.join("\n"));c.append(g);a.insertBefore(c,
a.firstChild);a.insertBefore(document.createElement("br"),a.firstChild)}function d(a,c,g,k){let b="";k&&(b="// ");ia[a]||(b+=T+" ",k||(ia[a]=1));b+=a+" = "+c+";";g&&(b+="  // "+g);Y.push(b)}function G(a){switch(E){case 0:case 1:case 2:return n("srli_"+C,a,4);case 3:return n("bsrli_epi128",a,4)}}function Z(a,c){switch(E){case 0:return n("unpackhi_epi64",n("unpacklo_epi32",a,c),n("unpackhi_epi32",a,c));case 1:return ea("blend_epi16",[G(a),c,"0xCC"]);case 2:return ea("blend_epi32",[G(a),c,"0xAA"]);case 3:return ea("mask_blend_epi32",
["0xAAAA",G(a),c])}}function ja(a,c){switch(E){case 0:return n("unpacklo_epi64",n("unpacklo_epi32",a,c),n("unpackhi_epi32",a,c));default:throw"internal error";}}function P(a,c){const g=(r,q)=>{let u=!1,p,x=0,fa=[];for(;x<K;x++)u?(q&1)!=r&&(fa.push([p,x-p]),u=!1):(q&1)==r&&(p=x,u=!0),q>>>=1;u&&fa.push([p,K-p]);return fa};var k=a,b=a;for(a=0;a<K&&!(b&1);a++)b>>>=1,k>>=1;var f=r=>{let q=[],u=[];g(1,r).forEach(p=>{if(2>=p[1])for(let x=0;x<p[1];x++)q.push(p[0]+x);else u.push(p[0]),p[0]+p[1]<K&&q.push(p[0]+
p[1])});return[q,u]},h=r=>{let q=[],u=[];u.push(0);g(0,r).forEach(p=>{if(2>=p[1])for(let x=0;x<p[1];x++)u.push(p[0]+x);else q.push(p[0]),p[0]+p[1]<K&&u.push(p[0]+p[1])});return[q,u]},e=[];e.push(f(b));e.push(h(k));k!=b&&(e.push(f(k)),e.push(h(b)));h=r=>{let q=0;r.forEach(u=>u.forEach(p=>{p&&q++}));return(r[1].length&&0==r[0].length?1:0)+Math.max(r[0].length-1,0)+r[1].length+q};f=2147483647;let t;for(var v=0;v<e.length;v++){var H=h(e[v]);if(H<f){f=H;var U=e[v];t=!1}var z=[e[v][1],e[v][0]];H=h(z);H<
f&&(f=H,U=z,t=!0)}f+=a?1:0;v=4+(a?1:0);let D=[];const V=()=>D.length?"t":"quotients";let aa,L;0==B?(e=I,aa=y,L=ka):(e=M,aa=N,L=la);h=!1;if(v<f){if(v>c)return!1;v=r=>{let q=[];for(let u=0;u<K;u++)r&1&&q.push(u),r>>>=1;return 4==q.length&&q[1]-q[0]==q[3]-q[2]?[q[1]-q[0],q[2]-q[0]]:null};H=!1;z=v(k);z||(z=v(b),z||(H=!0,(z=v(-k))||(z=v(-b))));z&&(D.push(e(V(),L("quotients",z[0]))),D.push(e("t",L("t",z[1]))),t=H,h=!0)}if(!h){if(f>c)return!1;c=U[0];U=U[1];if(c.length)for(k=0;k<c.length;k++)if(b=c[k])b=
L("quotients",b),0==k?D.push(b):D.push(e(V(),b));else{if(0<k)throw"internal error";}else D.push(w+"_setzero_"+C+"()");U.forEach(r=>{r=r?L("quotients",r):"quotients";D.push(aa(V(),r))})}a&&D.push(L(V(),a));for(a=0;a<D.length;a++)d("t",D[a]);d("remainders",(t?e:aa)("dividends",V()));return!0}function ra(){for(var a=document.getElementById("msgdiv");a.lastChild;)a.removeChild(a.lastChild);E=document.getElementById("instructionset").selectedIndex;W=document.getElementById("datatypesign").selectedIndex;
B=document.getElementById("datatypesize").selectedIndex;K=0==B?32:16;F=document.getElementById("check_remainders").checked;m=parseInt(document.getElementById("divisor").value);if(isNaN(m))throw'divisor must be a decimal string or a hexadecimal string with leading "0x"';if(0==m)throw"divisor cannot be 0";if(0==W)if(0==B){a=-2147483648;var c=2147483647}else a=-32768,c=32767;else a=0,c=0==B?4294967295:65535;if(m<a||m>c)throw"divisor out of range";a=Math.abs(m);switch(E){case 0:case 1:ba=0==E?"SSE2":
"SSE4.1";T="__m128i";ca=16;w="_mm";C="si128";break;case 2:ba="AVX2";T="__m256i";ca=32;w="_mm256";C="si256";break;case 3:ba="AVX-512",T="__m512i",ca=64,w="_mm512",C="si512"}c=0==W?"signed":"unsigned";var g=0==B?"DWORD":"WORD";let k=ca/(0==B?4:2);Y.push("// "+c+" "+g+" integer division by constant "+m+" ("+ba+")");Y.push("// "+T+" dividends "+k+" "+c+" "+g+"s");if(1==a)throw"divisor out of range";c=1;for(g=2;g<=a;){if(g==a){if(0==W)if(0==B){var b=c;a=0>m;1==b?d("t",Q("dividends",31)):d("t",Q(X("dividends",
b-1),32-b));a?(d("t",X(I("dividends","t"),b)),d("quotients",y(w+"_setzero_"+C+"()","t"))):d("quotients",X(I("dividends","t"),b));F&&d("remainders",(a?I:y)("dividends",ka("quotients",b)))}else b=c,a=0>m,1==b?d("t",R("dividends",15)):d("t",R(da("dividends",b-1),16-b)),a?(d("t",da(M("dividends","t"),b)),d("quotients",N(w+"_setzero_"+C+"()","t"))):d("quotients",da(M("dividends","t"),b)),F&&d("remainders",(a?M:N)("dividends",la("quotients",b)));else 0==B?(b=c,d("quotients",Q("dividends",b)),F&&(b=O((1<<
b)-1),b=n("and_"+C,"dividends",b),d("remainders",b))):(b=c,d("quotients",R("dividends",b)),F&&d("remainders",n("and_"+C,"dividends",w+"_set1_epi16("+((1<<b)-1)+")")));ha();return}c++;g*=2}if(0==W)0==B?(a=new ma(m),d("magic",O(a.M)),0==E?(d("t0",J("magic","dividends")),d("t1",J("magic",G("dividends"))),d("t",Z("t0","t1")),c=X("dividends",31),c=n("and_"+C,"magic",c),d("t",y("t",c),"convert to signed multiplication products"),0<m&&0>a.M&&(d("t",y("t","dividends"),"convert to signed multiplication products",
!0),d("t",I("t","dividends"),"(counteracting lines are commented out to show we don't forget to add)",!0)),0>m&&(0>a.M&&(b="convert to signed multiplication products"),d("t",y("t","dividends"),b))):(d("t0",n("mul_epi32","magic","dividends")),b=G("dividends"),b=n("mul_epi32","magic",b),d("t1",b),d("t",Z("t0","t1")),0<m?0>a.M&&d("t",I("t","dividends")):0<=a.M&&d("t",y("t","dividends"))),a.s&&d("t",X("t",a.s)),d("quotients",I("t",Q("t",31))),F&&(0==E?P(m,5)||(d("t",O(m&4294967295)),d("t0",J("quotients",
"t")),d("t1",J(G("quotients"),"t")),d("t",ja("t0","t1")),d("remainders",y("dividends","t"))):P(m,1)||(b=O(m&4294967295),b=n("mullo_epi32","quotients",b),d("remainders",y("dividends",b))))):(a=new na(m),b=n("mulhi_epi16",w+"_set1_epi16("+a.M+")","dividends"),d("t",b),0<m?0>a.M&&d("t",M("t","dividends")):0<=a.M&&d("t",N("t","dividends")),a.s&&d("t",da("t",a.s)),d("quotients",M("t",R("t",15))),F&&!P(S(m),1)&&(b=w+"_set1_epi16("+S(m)+")",b=n("mullo_epi16","quotients",b),d("remainders",N("dividends",b))));
else if(0==B){b=new oa(m);d("magic",O(b.M&4294967295));d("t0",J("magic","dividends"));d("t1",J("magic",G("dividends")));a=b.s;b.a&&a--;if(a)d("t",Z("t0","t1")),b.a&&d("t",I("t",Q(y("dividends","t"),1))),d("quotients",Q("t",a));else{if(b.a)throw"internal error";d("quotients",Z("t0","t1"))}b="";m&2147483648&&(b="(int)");F&&(0==E?P(m,5)||(d("t",O(b+m)),d("t0",J("quotients","t")),d("t1",J(G("quotients"),"t")),d("t",ja("t0","t1")),d("remainders",y("dividends","t"))):P(m,1)||(b=O(b+m),b=n("mullo_epi32",
"quotients",b),d("remainders",y("dividends",b))))}else{b=new pa(m);a=b.s;b.a&&a--;if(a)c=w+"_set1_epi16("+S(b.M)+")",c=n("mulhi_epu16",c,"dividends"),d("t",c),b.a&&d("t",M("t",R(N("dividends","t"),1))),d("quotients",R("t",a));else throw"internal error";b="";m&32768&&(b="(short)");F&&!P(S(m),1)&&(b=n("mullo_epi16","quotients",w+"_set1_epi16("+(b+m)+")"),d("remainders",N("dividends",b)))}ha()}const l=a=>{a&=4294967295;return 0<=a?a:a+4294967296},S=a=>{a&=65535;return a&32768?a-65536:a};let Y=[],ia=
[],E,W,B,K,m,F,ba,T,ca,w,C;const n=(a,c,g)=>w+"_"+a+"("+c+", "+g+")",ea=(a,c)=>w+"_"+a+"("+c.join(", ")+")",O=a=>w+"_set1_epi32("+a+")",I=(a,c)=>n("add_epi32",a,c),y=(a,c)=>n("sub_epi32",a,c),J=(a,c)=>n("mul_epu32",a,c),X=(a,c)=>n("srai_epi32",a,c),Q=(a,c)=>n("srli_epi32",a,c),ka=(a,c)=>n("slli_epi32",a,c),M=(a,c)=>n("add_epi16",a,c),N=(a,c)=>n("sub_epi16",a,c),da=(a,c)=>n("srai_epi16",a,c),R=(a,c)=>n("srli_epi16",a,c),la=(a,c)=>n("slli_epi16",a,c);try{ra()}catch(a){qa(a.toString())}};
